### ISSUE TITLE
Circle CI configuration

### ISSUE THREAD

**Issue by jshrt** [invisible-tech/njord#5]
I was looking at the circle ci configuration and it needs some love, wanna assign this to someone @kewitz?

Thanks

**Comment by kewitz** [comment]
@jshrt what do you mean?

**Comment by jshrt** [comment]
Right now there is only a single job named build, where as we should lint, build, test and deploy to dockerhub.

**Comment by rodrigo4244** [comment]
https://github.com/invisible-tech/njord/pull/7
